version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aegir
    versions:
    - 30.3.0
    - 31.0.0
    - 31.0.1
    - 31.0.3
    - 31.0.4
    - 32.0.2
    - 33.0.0
    - 33.1.0
  - dependency-name: "@types/sinon"
    versions:
    - 10.0.0
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 10.0.1
  - dependency-name: ipld-dag-pb
    versions:
    - 0.22.1
    - 0.22.2
  - dependency-name: bl
    versions:
    - 5.0.0
  - dependency-name: ipld
    versions:
    - 0.29.0
  - dependency-name: ipld-in-memory
    versions:
    - 8.0.0
  - dependency-name: multicodec
    versions:
    - 3.0.1
  - dependency-name: it-buffer-stream
    versions:
    - 2.0.0
  - dependency-name: ipfs-utils
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: err-code
    versions:
    - 3.0.0
    - 3.0.1
  - dependency-name: uint8arrays
    versions:
    - 2.0.5
    - 2.1.0
    - 2.1.2
