language: node_js
cache: npm

branches:
  only:
  - master
  - /^release\/.*$/

services:
  - xvfb

stages:
  - check
  - test
  - cov
  - release

node_js:
  - 'node'
  - 'lts/*'

os:
  - linux
  - osx
  - windows

before_install:
  # prevents windows error: npm ERR! ... git-sh-setup: file not found
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH=/c/PROGRA~1/Git/usr/bin:/c/PROGRA~1/Git/mingw64/libexec/git-core:$PATH ; fi

script: npx nyc -s npm run test -- -- -- -t node --bail
after_success: npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov

jobs:
  include:
    - stage: check
      name: linting
      script:
        - npm run lint

    - stage: check
      name: dep-check (production deps)
      script:
        - npm run depcheck -- $RUN_SINCE -- -- -p

    - stage: check
      name: dep-check (unused deps)
      script:
        - npm run depcheck -- $RUN_SINCE -- -- -- --unused

    - stage: test
      name: chrome
      addons:
        chrome: stable
      script: npm run test -- -- -- -t browser

    - stage: test
      name: chrome webworker
      addons:
        chrome: stable
      script: npm run test -- -- -- -t webworker

    - stage: test
      name: firefox
      addons:
        firefox: latest
      script: npm run test -- -- -- -t browser --browsers FirefoxHeadless

    - stage: test
      name: firefox webworker
      addons:
        firefox: latest
      script: npm run test -- -- -- -t webworker --browsers FirefoxHeadless

    - stage: test
      name: electron main
      addons:
        firefox: latest
      script: npm run test -- -- -- -t electron-main

    - stage: release
      # only run on changes to master
      if: branch = master AND type = push AND fork = false
      name: release rc
      script:
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        - npm run release:rc -- --yes

notifications:
  email: false
